### ISSUE TITLE
don't compile

### ISSUE THREAD

**Issue by denk1** [vazgriz/VoxelGame#1]
Why I've got compile error 
../../Game/shaders/shader.vert: 3: Syntax error: word unexpected (expecting ")")
make[2]: *** [Game/CMakeFiles/CompileShaders.dir/build.make:66: Game/shaders/shader.vert.spv] Error 2
make[1]: *** [CMakeFiles/Makefile2:265: Game/CMakeFiles/CompileShaders.dir/all] Error 2

**Comment by vazgriz** [comment]
What compiler are you using for the GLSL?
Do you have it set in the CMake variable `GLSL_COMPILER`?

**Comment by denk1** [comment]
> What compiler are you using for the GLSL?
> Do you have it set in the CMake variable `GLSL_COMPILER`?

What should GLSL_COMPILER set value for an example?

**Comment by denk1** [comment]
Ok, I've installed glslang-tools and this problem was resolved.

**Comment by denk1** [comment]
After that I'd set -DGLSL_COMPILER=/usr/bin/glslangValidator
Now, it gets the output:

/usr/bin/glslangValidator: Error: no binary generation requested (e.g., -V) (use -h for usage)
make[2]: *** [Game/CMakeFiles/CompileShaders.dir/build.make:66: Game/shaders/shader.vert.spv] Error 1
make[1]: *** [CMakeFiles/Makefile2:265: Game/CMakeFiles/CompileShaders.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by vazgriz** [comment]
Ok I see what the problem is. I designed the project to use `glslc`, not `glslangValidator`. So for a quick solution, set `GLSL_COMPILER` to `glslc`. That program should be a part of the Vulkan SDK too.

I can add support for glslValidator later. I'm also going to add to the read me to clarify this.

**Comment by denk1** [comment]
it has helped. Thx.
